html:
  favicon: "figures/TB_favicon.ico"
  baseurl: "https://teachbooks.io/" # Replace this with your own URL
  extra_css:
    - _static/custom.css

sphinx:
  config:
    # ⚠️ Remove require.js (causes MathJax conflicts)
    html_js_files: []

    mathjax3_config:
      tex:
        inlineMath: [["$", "$"], ["\\(", "\\)"]]
        displayMath: [["$$", "$$"], ["\\[", "\\]"]]
      startup:
        ready: function () {
          MathJax.startup.defaultReady();
          MathJax.typesetPromise();
        }

    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]

    html_theme_options:
      logo:
        text: Template
        image_light: TeachBooks_logo.svg # Logo for light mode
        image_dark: TeachBooks_logo_inverted.svg # Logo for dark mode
      repository_url: "https://github.com/user/repo" # Add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button: true
      launch_buttons:
        thebe: true

    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    html_static_path: 
      - figures   # Include figures folder
      - _static   # Include the _static folder where custom.css is stored
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_exercise
    - teachbooks_sphinx_tippy

bibtex_bibfiles: 
  - references.bib
