name: Build and Deploy Book

on:
  push:
    branches:
      - '**'
    paths:
      - book/**
      - requirements.txt
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  parse-references:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List repository structure
        run: |
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -U pip
          # If you need other libs, install them here

      - name: Parse references
        run: |
          python book/parse_references.py

      - name: Copy references into build folder
        run: |
          cp references.txt book/_build/html/references.txt || true

      - name: Build Jupyter Book
        run: |
          jupyter-book build book/

  call-workflow:
    name: Deploy Book
    needs: parse-references
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
