name: call-deploy-book

on:
  push:
    branches:
      - '**'
    paths:
      - book/**
      - requirements.txt
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  parse-references:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (if needed)
        run: |
          pip install -U pip

      - name: List repository structure
        run: |
          ls -R

      - name: Parse references and tags
        run: |
          python book/parse_references.py

      - name: Copy references and tags into book/
        run: |
          cp references.txt book/references.txt || true
          cp tags.txt book/tags.txt || true

      - name: Upload references artifact
        uses: actions/upload-artifact@v4
        with:
          name: references
          path: references.txt

      - name: Upload tags artifact
        uses: actions/upload-artifact@v4
        with:
          name: tags
          path: tags.txt

  call-workflow:
    name: Deploy Book
    needs: parse-references
    uses: ./.github/workflows/deploy-book.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
