name: call-deploy-book

on:
  push:
    branches:
      - '**'
    paths:
      - book/**
      - requirements.txt
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  parse-references:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: List repository structure
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -U pip
          # If you need other libs, install them here

      - name: Parse references
        run: |
          python book/parse_references.py

      # Now references.txt sits in the repo root if parse_references.py wrote it there,
      # or in 'book/' if that's how your script is set up.
      - name: Copy references.txt into the _build/html folder
        run: |
          cp references.txt book/_build/html/references.txt
          # or if your script wrote it to book/, do:
          # cp book/references.txt book/_build/html/references.txt

      # Now build the book, which includes references.txt
      - name: Build Jupyter Book
        run: |
          jupyter-book build book/

      - name: Deploy
        # your usual deploy or call-workflow step

  call-workflow:
    name: Deploy Book
    needs: parse-references
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
